name: SoosSystem
author: CheckerPhil
version: 1.0
main: de.CheckerPhil.soos.SoosSystem
api-version: 1.19
commands:
  ping:
  report:
  kick:
  ban:
  baninfo:
  brodcast:
    aliases: [bc]
  unban:
  mute:
  nick:
  unnick:
  roundkick:
    aliases: [ rkick ]
  undercoverban:
    aliases: [ ucban ]
